/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class CLMenu extends javax.swing.JFrame {

    /**
     * Creates new form CLMenu
     */
    public CLMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCLMM = new javax.swing.JLabel();
        jButtonCLVP = new javax.swing.JButton();
        jButtonSLSP = new javax.swing.JButton();
        jButtonCLSS = new javax.swing.JButton();
        jButtonCLMB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCLMM.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCLMM.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCLMM.setText("|   Main  Menu   |");
        getContentPane().add(jLabelCLMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 303, 60));

        jButtonCLVP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCLVP.setText("View Product Details ");
        jButtonCLVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLVPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 314, 52));

        jButtonSLSP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSLSP.setText("Search Product Details");
        jButtonSLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSLSPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 314, 50));

        jButtonCLSS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCLSS.setText("Search Stock Details");
        jButtonCLSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLSSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 314, 49));

        jButtonCLMB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCLMB.setText("Back");
        jButtonCLMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLMBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 311, 93, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCLVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLVPActionPerformed
    new ViewProductCashire().setVisible(true);
    this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLVPActionPerformed

    private void jButtonSLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSLSPActionPerformed
    new SearchProductCashier().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSLSPActionPerformed

    private void jButtonCLSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLSSActionPerformed
    new SearchStockCashier().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLSSActionPerformed

    private void jButtonCLMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLMBActionPerformed
    CLogin p1  = new CLogin();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCLMB;
    private javax.swing.JButton jButtonCLSS;
    private javax.swing.JButton jButtonCLVP;
    private javax.swing.JButton jButtonSLSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCLMM;
    // End of variables declaration//GEN-END:variables
}
