
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class CLogin extends javax.swing.JFrame {

    /**
     * Creates new form CLogin
     */
    public CLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMCPIC = new javax.swing.JLabel();
        jLabelCLUN = new javax.swing.JLabel();
        jLabelCLPW = new javax.swing.JLabel();
        jTextFieldCLUN = new javax.swing.JTextField();
        jPasswordFieldCLPW = new javax.swing.JPasswordField();
        jButtonCLL = new javax.swing.JButton();
        jButtonCLB = new javax.swing.JButton();
        jButtonCLC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMCPIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user11.png"))); // NOI18N
        getContentPane().add(jLabelMCPIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 31, 220, 200));

        jLabelCLUN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCLUN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCLUN.setText("User Name   :");
        getContentPane().add(jLabelCLUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 244, 173, 42));

        jLabelCLPW.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCLPW.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCLPW.setText("Password    :");
        getContentPane().add(jLabelCLPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 300, 161, 44));

        jTextFieldCLUN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextFieldCLUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 244, 208, 42));

        jPasswordFieldCLPW.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPasswordFieldCLPW.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordFieldCLPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 304, 208, 36));

        jButtonCLL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCLL.setText("Login");
        jButtonCLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLLActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 234, 87, 36));

        jButtonCLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCLB.setText("Back");
        jButtonCLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 288, 88, 36));

        jButtonCLC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCLC.setText("Clear");
        jButtonCLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 342, 88, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLLActionPerformed
    String UserName,Password;
    UserName = jTextFieldCLUN.getText();
    Password = jPasswordFieldCLPW.getText();
    
    if(UserName.equals("Cashier123") && Password.equals("12345"))
    {
       setVisible(false);
       CLMenu object = new CLMenu();
       object.setVisible(true);     
    }
    else
    {
       JOptionPane.showConfirmDialog(null, "Invalid Username Or Password");
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLLActionPerformed

    private void jButtonCLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLBActionPerformed
    Main p1  = new Main();
    p1.setVisible(true);
    p1.toFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLBActionPerformed

    private void jButtonCLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLCActionPerformed
    jTextFieldCLUN.setText("");
    jPasswordFieldCLPW.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCLCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCLB;
    private javax.swing.JButton jButtonCLC;
    private javax.swing.JButton jButtonCLL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCLPW;
    private javax.swing.JLabel jLabelCLUN;
    private javax.swing.JLabel jLabelMCPIC;
    private javax.swing.JPasswordField jPasswordFieldCLPW;
    private javax.swing.JTextField jTextFieldCLUN;
    // End of variables declaration//GEN-END:variables
}
