/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class CreateAC extends javax.swing.JFrame {

    /**
     * Creates new form CreateAC
     */
    public CreateAC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCA = new javax.swing.JLabel();
        jLabelCAN = new javax.swing.JLabel();
        jLabelCAID = new javax.swing.JLabel();
        jLabelCAMN = new javax.swing.JLabel();
        jLabelCAUN = new javax.swing.JLabel();
        jLabelCAPW = new javax.swing.JLabel();
        jTextFieldCAN = new javax.swing.JTextField();
        jTextFieldCAID = new javax.swing.JTextField();
        jTextFieldCAMN = new javax.swing.JTextField();
        jTextFieldCAUN = new javax.swing.JTextField();
        jLabelCACPW = new javax.swing.JLabel();
        jPasswordFieldCAPW = new javax.swing.JPasswordField();
        jPasswordFieldCACPW = new javax.swing.JPasswordField();
        jButtonCAA = new javax.swing.JButton();
        jButtonCAC = new javax.swing.JButton();
        jButtonCAB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCA.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCA.setText("|   Create Account   |");
        getContentPane().add(jLabelCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 6, 388, 59));

        jLabelCAN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCAN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAN.setText("Name      :");
        getContentPane().add(jLabelCAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 83, 130, 32));

        jLabelCAID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCAID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAID.setText("ID           :");
        getContentPane().add(jLabelCAID, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 131, 130, 29));

        jLabelCAMN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCAMN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAMN.setText("Mobile No  :");
        getContentPane().add(jLabelCAMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 174, 120, 28));

        jLabelCAUN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCAUN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAUN.setText(" User_Name  :");
        getContentPane().add(jLabelCAUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 219, 130, 27));

        jLabelCAPW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCAPW.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCAPW.setText("Password    :");
        getContentPane().add(jLabelCAPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 275, 130, 28));

        jTextFieldCAN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldCAN.setToolTipText("");
        getContentPane().add(jTextFieldCAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 84, 204, 32));

        jTextFieldCAID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextFieldCAID, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 130, 204, 30));

        jTextFieldCAMN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextFieldCAMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 172, 204, 33));

        jTextFieldCAUN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextFieldCAUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 217, 204, 32));

        jLabelCACPW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCACPW.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCACPW.setText("Confirm Password :");
        getContentPane().add(jLabelCACPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 318, 172, 26));

        jPasswordFieldCAPW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jPasswordFieldCAPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 274, 204, -1));

        jPasswordFieldCACPW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jPasswordFieldCACPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 316, 204, -1));

        jButtonCAA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCAA.setText("Register");
        jButtonCAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCAAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 159, -1, 40));

        jButtonCAC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCAC.setText("Clear");
        jButtonCAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCACActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 75, 34));

        jButtonCAB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCAB.setText("Back");
        jButtonCAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCABActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 75, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCABActionPerformed
    MLMenu p1  = new MLMenu();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCABActionPerformed

    private void jButtonCACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCACActionPerformed
    jTextFieldCAN.setText("");
    jTextFieldCAID.setText("");
    jTextFieldCAMN.setText("");
    jTextFieldCAUN.setText("");
    jPasswordFieldCAPW.setText("");
    jPasswordFieldCACPW.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCACActionPerformed

    private void jButtonCAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCAAActionPerformed
    CreateAccountClass account = new CreateAccountClass ();
    account.setName(jTextFieldCAN.getText().toString());
    account.setID(jTextFieldCAID.getText().toString());
    account.setMobileNo(Integer .parseInt(jTextFieldCAMN.getText()));
    account.setUser_Name(jTextFieldCAUN.getText().toString());
    account.setPassword(jPasswordFieldCAPW.getText().toString());
    account.setConfirmPassword(jPasswordFieldCACPW.getText().toString());
    
    account.addAccount(account);
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCAAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCAA;
    private javax.swing.JButton jButtonCAB;
    private javax.swing.JButton jButtonCAC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCA;
    private javax.swing.JLabel jLabelCACPW;
    private javax.swing.JLabel jLabelCAID;
    private javax.swing.JLabel jLabelCAMN;
    private javax.swing.JLabel jLabelCAN;
    private javax.swing.JLabel jLabelCAPW;
    private javax.swing.JLabel jLabelCAUN;
    private javax.swing.JPasswordField jPasswordFieldCACPW;
    private javax.swing.JPasswordField jPasswordFieldCAPW;
    private javax.swing.JTextField jTextFieldCAID;
    private javax.swing.JTextField jTextFieldCAMN;
    private javax.swing.JTextField jTextFieldCAN;
    private javax.swing.JTextField jTextFieldCAUN;
    // End of variables declaration//GEN-END:variables
}
