/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class MLMenu extends javax.swing.JFrame {

    /**
     * Creates new form MLMenu
     */
    public MLMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMLCA = new javax.swing.JButton();
        jButtonMLAP = new javax.swing.JButton();
        jButtonMLVP = new javax.swing.JButton();
        jButtonMLSP = new javax.swing.JButton();
        jButtonMLSS = new javax.swing.JButton();
        jLabelMLMM = new javax.swing.JLabel();
        jButtonMLMB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMLCA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMLCA.setText("Create New Account");
        jButtonMLCA.setToolTipText("");
        jButtonMLCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLCAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 89, 299, 49));

        jButtonMLAP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMLAP.setText("Add Product Details");
        jButtonMLAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLAPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 150, 299, 45));

        jButtonMLVP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMLVP.setText("View Product Details");
        jButtonMLVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLVPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 207, 299, 45));

        jButtonMLSP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMLSP.setText("Search Product Details");
        jButtonMLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLSPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 264, 299, 46));

        jButtonMLSS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMLSS.setText("Search Stock Details");
        jButtonMLSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLSSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 322, 299, 43));

        jLabelMLMM.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelMLMM.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMLMM.setText("|   Main Menu   |");
        getContentPane().add(jLabelMLMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 6, 345, 57));

        jButtonMLMB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMLMB.setText("Back");
        jButtonMLMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLMBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 322, 85, 33));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMLCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLCAActionPerformed
    new CreateAC().setVisible(true);
    this.dispose();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLCAActionPerformed

    private void jButtonMLAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLAPActionPerformed
    new AddProduct().setVisible(true);
    this.dispose();
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLAPActionPerformed

    private void jButtonMLVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLVPActionPerformed
    new ViewProduct().setVisible(true);
    this.dispose();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLVPActionPerformed

    private void jButtonMLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLSPActionPerformed
    new SearchProduct().setVisible(true);
    this.dispose();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLSPActionPerformed

    private void jButtonMLSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLSSActionPerformed
    new SearchStock().setVisible(true);
    this.dispose();
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLSSActionPerformed

    private void jButtonMLMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLMBActionPerformed
    MLogin p1  = new MLogin();
    p1.setVisible(true);
    p1.toFront();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MLMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MLMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMLAP;
    private javax.swing.JButton jButtonMLCA;
    private javax.swing.JButton jButtonMLMB;
    private javax.swing.JButton jButtonMLSP;
    private javax.swing.JButton jButtonMLSS;
    private javax.swing.JButton jButtonMLVP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMLMM;
    // End of variables declaration//GEN-END:variables
}
