
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class MLogin extends javax.swing.JFrame {

    /**
     * Creates new form MLogin
     */
    public MLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMLUN = new javax.swing.JLabel();
        jLabelMLPW = new javax.swing.JLabel();
        jTextFieldMLUN = new javax.swing.JTextField();
        jPasswordFieldMLPW = new javax.swing.JPasswordField();
        jButtonMLL = new javax.swing.JButton();
        jButtonMLB = new javax.swing.JButton();
        jButtonMLC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelPIC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMLUN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMLUN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMLUN.setText("User Name  :");
        getContentPane().add(jLabelMLUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 254, 151, 43));

        jLabelMLPW.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMLPW.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMLPW.setText("Password   :");
        getContentPane().add(jLabelMLPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 303, 151, 39));

        jTextFieldMLUN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextFieldMLUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 257, 206, -1));

        jPasswordFieldMLPW.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jPasswordFieldMLPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 303, 206, -1));

        jButtonMLL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMLL.setText("Login");
        jButtonMLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLLActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 260, 87, 37));

        jButtonMLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMLB.setText("Back");
        jButtonMLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 308, 87, 34));

        jButtonMLC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonMLC.setText("Clear");
        jButtonMLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMLCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 354, 87, 31));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user11.png"))); // NOI18N
        jPanel1.add(jLabelPIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 40, 230, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLLActionPerformed
    String UserName,Password;
    UserName = jTextFieldMLUN.getText();
    Password = jPasswordFieldMLPW.getText();
    
    if(UserName.equals("himashi123") && Password.equals("12345"))
    {  JOptionPane.showConfirmDialog(null,"Loging Successfully");
       setVisible(false);
       MLMenu object = new MLMenu();
       object.setVisible(true);     
    }
    else
    {
        JOptionPane.showConfirmDialog(null,"invalid Username & Password");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLLActionPerformed

    private void jButtonMLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLBActionPerformed
    Main p1  = new Main();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLBActionPerformed

    private void jButtonMLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMLCActionPerformed
    jTextFieldMLUN.setText("");
    jPasswordFieldMLPW.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMLCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMLB;
    private javax.swing.JButton jButtonMLC;
    private javax.swing.JButton jButtonMLL;
    private javax.swing.JLabel jLabelMLPW;
    private javax.swing.JLabel jLabelMLUN;
    private javax.swing.JLabel jLabelPIC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldMLPW;
    private javax.swing.JTextField jTextFieldMLUN;
    // End of variables declaration//GEN-END:variables
}
