
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class SearchStockCashier extends javax.swing.JFrame {

    /**
     * Creates new form SearchStockCashier
     */
    public SearchStockCashier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSS2 = new javax.swing.JLabel();
        jButtonSS2B = new javax.swing.JButton();
        jButtonSS2V = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSS2T = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSS2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelSS2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSS2.setText("|   Search Stock Details   |");
        getContentPane().add(jLabelSS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 6, 454, 58));

        jButtonSS2B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSS2B.setText("Back");
        jButtonSS2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSS2BActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSS2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 325, 87, 40));

        jButtonSS2V.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSS2V.setText("View");
        jButtonSS2V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSS2VActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSS2V, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 325, 87, 40));

        jTableSS2T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableSS2T);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 91, 520, 216));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSS2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSS2BActionPerformed
    CLMenu p1  = new CLMenu();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSS2BActionPerformed

    private void jButtonSS2VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSS2VActionPerformed

    String FILE = "D:\\Apple_iStore\\AppleStock.txt";
    File file = new File(FILE);
    
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTableSS2T.getModel();
            model.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) 
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(SearchStockCashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSS2VActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<edjButtonSS2d defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStockCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStockCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStockCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStockCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchStockCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSS2B;
    private javax.swing.JButton jButtonSS2V;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSS2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSS2T;
    // End of variables declaration//GEN-END:variables
}
