
import java.io.*;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class SearchProductCashier extends javax.swing.JFrame {

    /**
     * Creates new form SearchProductCashier
     */
    public SearchProductCashier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSP2 = new javax.swing.JLabel();
        jLabelSP2ID = new javax.swing.JLabel();
        jTextFieldSP2ID = new javax.swing.JTextField();
        jButtonSP2B = new javax.swing.JButton();
        jButtonSP2S = new javax.swing.JButton();
        jButtonSP2C = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSP2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelSP2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSP2.setText("|   Search Product Details   |");
        getContentPane().add(jLabelSP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 6, -1, 58));

        jLabelSP2ID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSP2ID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSP2ID.setText("Product ID  :");
        getContentPane().add(jLabelSP2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 181, 44));

        jTextFieldSP2ID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextFieldSP2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 245, 36));

        jButtonSP2B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSP2B.setText("Back");
        jButtonSP2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSP2BActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSP2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jButtonSP2S.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSP2S.setText("Search");
        jButtonSP2S.setActionCommand("");
        jButtonSP2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSP2SActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSP2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jButtonSP2C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSP2C.setText("Clear");
        jButtonSP2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSP2CActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSP2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jTableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableSP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 450, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSP2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSP2BActionPerformed
    CLMenu p1  = new CLMenu();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSP2BActionPerformed

    private void jButtonSP2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSP2CActionPerformed
    jTextFieldSP2ID.setText("");    
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSP2CActionPerformed

    private void jButtonSP2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSP2SActionPerformed
    String filePath = "D:\\Apple_iStore\\AppleiStoreProduct.txt";
    findData(jTextFieldSP2ID.getText().toString(), filePath);

    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSP2SActionPerformed
    
    public void findData(String searchWord, String filePath)
    {
    try{   BufferedReader in = new BufferedReader(
                 new FileReader(filePath));
         
             
      DefaultTableModel tblmodel = (DefaultTableModel)jTableSP.getModel();
      String firstLine = in.readLine().trim();
      String[] columnsName = firstLine.split(",");
          
      tblmodel.setColumnIdentifiers(columnsName);
      String line;
      while ((line = in.readLine()) != null)
      {
       
        // extract by lines and write to file
          line = line.trim();
        String firstColumn =  line.split(",")[0];
        if (firstColumn.contains(searchWord))
        {
            //line.replaceAll("\\s", "");
            
            String[] dataRow = line.split(",");          
   
            tblmodel.addRow(dataRow);
            
        }

      }
    }
    catch (IOException ex){
    
      ex.printStackTrace();
    }
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchProductCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchProductCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchProductCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchProductCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchProductCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSP2B;
    private javax.swing.JButton jButtonSP2C;
    private javax.swing.JButton jButtonSP2S;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSP2;
    private javax.swing.JLabel jLabelSP2ID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSP;
    private javax.swing.JTextField jTextFieldSP2ID;
    // End of variables declaration//GEN-END:variables

    private void findData2(String toString, String filePath) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
