
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class ViewProductCashire extends javax.swing.JFrame {

    private String ProductsClass;
    private String Products;

    /**
     * Creates new form ViewProductCashire
     */
    public ViewProductCashire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVP2 = new javax.swing.JLabel();
        jButtonVP2B = new javax.swing.JButton();
        jButtonVP2V = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVPCT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelVP2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelVP2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVP2.setText("|   View Product Details   |");
        getContentPane().add(jLabelVP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 6, 440, 50));

        jButtonVP2B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVP2B.setText("Back");
        jButtonVP2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVP2BActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVP2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jButtonVP2V.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVP2V.setText("View");
        jButtonVP2V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVP2VActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVP2V, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jTableVPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableVPCT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 74, 527, 238));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVP2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVP2BActionPerformed
    CLMenu p1  = new CLMenu();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVP2BActionPerformed

    private void jButtonVP2VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVP2VActionPerformed
    
    String FILE = "D:\\Apple_iStore\\AppleiStoreProduct.txt";
    File file = new File(FILE);
    
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTableVPCT.getModel();
            model.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) 
            {
               String line = tableLines[i].toString().trim();
               String[] dataRow = line.split(",");
               model.addRow(dataRow);
            }
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ViewProductCashire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVP2VActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProductCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProductCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProductCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProductCashire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProductCashire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVP2B;
    private javax.swing.JButton jButtonVP2V;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVP2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVPCT;
    // End of variables declaration//GEN-END:variables

    private void model(String[] dataRow) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
