
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Himashi
 */
public class ViewProduct extends javax.swing.JFrame {

    private String ProductsClass;

    /**
     * Creates new form ViewProduct
     */
    public ViewProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVP = new javax.swing.JLabel();
        jButtonVPB = new javax.swing.JButton();
        jButtonVPV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVPT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelVP.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelVP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVP.setText("|   View Product Details   |");
        getContentPane().add(jLabelVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 443, 51));

        jButtonVPB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVPB.setText("Back");
        jButtonVPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVPBActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 90, 40));

        jButtonVPV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonVPV.setText("View");
        jButtonVPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVPVActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 90, 40));

        jTableVPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTableVPT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVPBActionPerformed
    MLMenu p1  = new MLMenu();
    p1.setVisible(true);
    p1.toFront();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVPBActionPerformed

    private void jButtonVPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVPVActionPerformed
    String FILE="D:\\Apple_iStore\\AppleiStoreProduct.txt";
    File file = new File(FILE);
    
        try {
            BufferedReader br=new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName= firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTableVPT.getModel();
            model.setColumnIdentifiers(columnsName);
            
            Object[]tableLines = br.lines().toArray();
            
            for(int i=0; i<tableLines.length; i++)
            {
                String line =tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
                
            }
            
            
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ViewProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVPVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVPB;
    private javax.swing.JButton jButtonVPV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVPT;
    // End of variables declaration//GEN-END:variables

    private void model(String[] dataRow) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
